# Generated by Django 3.0.6 on 2020-06-13 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='all_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Category')),
            ],
        ),
        migrations.CreateModel(
            name='RequestVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('request_image', models.ImageField(null=True, upload_to='request_verification_images')),
                ('status', models.CharField(choices=[('User-Verified', 'User-Verified'), ('Non-Verified', 'Non-Verified')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100, null=True)),
                ('phone_no', models.CharField(max_length=13, null=True, unique=True)),
                ('job_completed', models.IntegerField(default=0)),
                ('address', models.TextField(blank=True, default=' ', null=True)),
                ('service_charge', models.CharField(blank=True, max_length=10, null=True)),
                ('logo', models.ImageField(null=True, upload_to='professional_photo')),
                ('joining_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sub_category', models.ManyToManyField(blank=True, to='account.SubCategory')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('package_image', models.ImageField(null=True, upload_to='package_images')),
                ('cost', models.FloatField(default=0.0)),
                ('cost_factor', models.FloatField(default=1.0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
